In [1]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from IPython.display import Image

In [89]:
# create array and save it as a textfile
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
np.savetxt("text.txt",arr1,delimiter =',')

In [94]:
# open file in read mode
f =open("text.txt",'r')
print(f.read())

1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00
7.000000000000000000e+00,8.000000000000000000e+00,9.000000000000000000e+00



In [99]:
#Convert a list into an array
a = [1,2,3,4]
print(type(a))
b = np.asarray(a)
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [100]:
# array converted to a float type.
x = np.array([[1, 2], [3, 4]])
print(x)
print(np.asfarray(x))

[[1 2]
 [3 4]]
[[1. 2.]
 [3. 4.]]


In [101]:
# Array to be divided into sub-array
x = np.arange(9.0)
print(x)
y,z,n = np.split(x, 3)
print(y)
print(z)
print(n)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]
[0. 1. 2.]
[3. 4. 5.]
[6. 7. 8.]


In [103]:
# dsplit
x = np.arange(16.0).reshape(2, 2, 4)
print(x)

[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]]

 [[ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]]


In [104]:
print(np.dsplit(x, 2))

[array([[[ 0.,  1.],
        [ 4.,  5.]],

       [[ 8.,  9.],
        [12., 13.]]]), array([[[ 2.,  3.],
        [ 6.,  7.]],

       [[10., 11.],
        [14., 15.]]])]


In [71]:
# Return a new array with sub-arrays along an axis deleted
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
np.delete(arr, 1,0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [107]:
# Insert values along the given axis before the given indices
a = np.array([[1, 1], [2, 2], [3, 3]])
print(a)

[[1 1]
 [2 2]
 [3 3]]


In [109]:
np.insert(a, 1, 5, axis=1)

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

In [88]:
# Roll array elements along a given axis.
x = np.arange(10)
print(x)
print(np.roll(x, 2))

[0 1 2 3 4 5 6 7 8 9]
[8 9 0 1 2 3 4 5 6 7]


In [87]:
# Return a copy of a with only the first character of each element capitalized
c = np.array(['a1b2','1b2a','b2a1','2a1b'])
print(c)
print(np.char.capitalize(c))

['a1b2' '1b2a' 'b2a1' '2a1b']
['A1b2' '1b2a' 'B2a1' '2a1b']


In [111]:
# Return an array with the elements converted to lowercase.
c = np.array(['A1B C', '1BCA', 'BCA1'])
print(c)
print(np.char.lower(c))

['A1B C' '1BCA' 'BCA1']
['a1b c' '1bca' 'bca1']


In [112]:
# Return an array with the elements converted to uppercase.
c = np.array(['A1b c', '1bcA', 'BCa1'])
print(c)
print(np.char.upper(c))

['A1b c' '1bcA' 'BCa1']
['A1B C' '1BCA' 'BCA1']


In [114]:
# return a copy with the leading characters removed
c = np.array(['aAaAaA', ' aA ', 'abBABba'])
print(c)
print(np.char.lstrip(c, 'a'))

['aAaAaA' ' aA ' 'abBABba']
['AaAaA' ' aA ' 'bBABba']


In [118]:
# return a copy with the trailing characters removed.
c = np.array(['aAaAaA', 'abBABba'])
print(c)
print(np.char.rstrip(c, 'a'))

['aAaAaA' 'abBABba']
['aAaAaA' 'abBABb']


In [121]:
# return a copy with the leading and trailing characters removed.
c = np.array([' aAaAaA ', ' aA ', ' abBABba '])
print(c)
print(np.char.strip(c))

[' aAaAaA ' ' aA ' ' abBABba ']
['aAaAaA' 'aA' 'abBABba']


In [122]:
# Take elements from an array along an axis
a = [4, 3, 5, 7, 6, 8]
print(a)
indices = [0, 1, 4]
print(np.take(a, indices))

[4, 3, 5, 7, 6, 8]
[4 3 6]


In [131]:
# Change elements of an array based on conditional and input values.
arr = np.arange(6).reshape(2, 3)
print(arr)
np.place(arr, arr>2, [44, 55])
arr

[[0 1 2]
 [3 4 5]]


array([[ 0,  1,  2],
       [44, 55, 44]])

In [133]:
# Changes elements of an array based on conditional and input values.
x = np.arange(6).reshape(2, 3)
print(x)
np.putmask(x, x>2, x**2)
x

[[0 1 2]
 [3 4 5]]


array([[ 0,  1,  2],
       [ 9, 16, 25]])

In [145]:
# Flat iterator object to iterate over arrays.
x = np.arange(6).reshape(2, 3)
print(x)

fl = x.flat
for item in fl:
    print(item)

[[0 1 2]
 [3 4 5]]
0
1
2
3
4
5


In [151]:
# DataSource([destpath]) A generic data source file (file, http, ftp, ...).
repos = np.DataSource()

In [152]:
repos.exists('www.google.com/index.html')

False

In [153]:
repos.exists('http://www.google.com/index.html')

True